/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SystemSettingsRouteImport } from './routes/system-settings'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SubscribeFilesRouteImport } from './routes/subscribe-files'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProbeRouteImport } from './routes/probe'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomRulesRouteImport } from './routes/custom-rules'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as SubscriptionIndexRouteImport } from './routes/subscription.index'
import { Route as SubscribeFilesIndexRouteImport } from './routes/subscribe-files.index'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as CustomRulesIndexRouteImport } from './routes/custom-rules.index'
import { Route as SubscribeFilesCustomRouteImport } from './routes/subscribe-files.custom'
import { Route as DocsUsersRouteImport } from './routes/docs/users'
import { Route as DocsUpdateRouteImport } from './routes/docs/update'
import { Route as DocsTrafficInfoRouteImport } from './routes/docs/traffic-info'
import { Route as DocsTemplatesRouteImport } from './routes/docs/templates'
import { Route as DocsSystemSettingsRouteImport } from './routes/docs/system-settings'
import { Route as DocsSystemRequirementsRouteImport } from './routes/docs/system-requirements'
import { Route as DocsSubscriptionLinkRouteImport } from './routes/docs/subscription-link'
import { Route as DocsSubscribeFilesRouteImport } from './routes/docs/subscribe-files'
import { Route as DocsSettingsRouteImport } from './routes/docs/settings'
import { Route as DocsQuickStartRouteImport } from './routes/docs/quick-start'
import { Route as DocsProxyProvidersAdvancedRouteImport } from './routes/docs/proxy-providers-advanced'
import { Route as DocsProxyProvidersRouteImport } from './routes/docs/proxy-providers'
import { Route as DocsProbeRouteImport } from './routes/docs/probe'
import { Route as DocsNodesRouteImport } from './routes/docs/nodes'
import { Route as DocsLoginRouteImport } from './routes/docs/login'
import { Route as DocsInstallDockerRouteImport } from './routes/docs/install-docker'
import { Route as DocsInstallDirectRouteImport } from './routes/docs/install-direct'
import { Route as DocsImportSubscriptionRouteImport } from './routes/docs/import-subscription'
import { Route as DocsGeneratorRouteImport } from './routes/docs/generator'
import { Route as DocsFeaturesRouteImport } from './routes/docs/features'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsExternalSubscriptionsRouteImport } from './routes/docs/external-subscriptions'
import { Route as DocsEditNodesRouteImport } from './routes/docs/edit-nodes'
import { Route as DocsCustomRulesRouteImport } from './routes/docs/custom-rules'
import { Route as DocsClientSetupRouteImport } from './routes/docs/client-setup'
import { Route as DocsChainProxyRouteImport } from './routes/docs/chain-proxy'
import { Route as DocsAboutRouteImport } from './routes/docs/about'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeFilesRoute = SubscribeFilesRouteImport.update({
  id: '/subscribe-files',
  path: '/subscribe-files',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeRoute = ProbeRouteImport.update({
  id: '/probe',
  path: '/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRulesRoute = CustomRulesRouteImport.update({
  id: '/custom-rules',
  path: '/custom-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const SubscriptionIndexRoute = SubscriptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscriptionRoute,
} as any)
const SubscribeFilesIndexRoute = SubscribeFilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscribeFilesRoute,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NodesRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const CustomRulesIndexRoute = CustomRulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomRulesRoute,
} as any)
const SubscribeFilesCustomRoute = SubscribeFilesCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => SubscribeFilesRoute,
} as any)
const DocsUsersRoute = DocsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUpdateRoute = DocsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTrafficInfoRoute = DocsTrafficInfoRouteImport.update({
  id: '/traffic-info',
  path: '/traffic-info',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTemplatesRoute = DocsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSystemSettingsRoute = DocsSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSystemRequirementsRoute = DocsSystemRequirementsRouteImport.update({
  id: '/system-requirements',
  path: '/system-requirements',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSubscriptionLinkRoute = DocsSubscriptionLinkRouteImport.update({
  id: '/subscription-link',
  path: '/subscription-link',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSubscribeFilesRoute = DocsSubscribeFilesRouteImport.update({
  id: '/subscribe-files',
  path: '/subscribe-files',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSettingsRoute = DocsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickStartRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProxyProvidersAdvancedRoute =
  DocsProxyProvidersAdvancedRouteImport.update({
    id: '/proxy-providers-advanced',
    path: '/proxy-providers-advanced',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsProxyProvidersRoute = DocsProxyProvidersRouteImport.update({
  id: '/proxy-providers',
  path: '/proxy-providers',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProbeRoute = DocsProbeRouteImport.update({
  id: '/probe',
  path: '/probe',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNodesRoute = DocsNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLoginRoute = DocsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallDockerRoute = DocsInstallDockerRouteImport.update({
  id: '/install-docker',
  path: '/install-docker',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallDirectRoute = DocsInstallDirectRouteImport.update({
  id: '/install-direct',
  path: '/install-direct',
  getParentRoute: () => DocsRoute,
} as any)
const DocsImportSubscriptionRoute = DocsImportSubscriptionRouteImport.update({
  id: '/import-subscription',
  path: '/import-subscription',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGeneratorRoute = DocsGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFeaturesRoute = DocsFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExternalSubscriptionsRoute =
  DocsExternalSubscriptionsRouteImport.update({
    id: '/external-subscriptions',
    path: '/external-subscriptions',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsEditNodesRoute = DocsEditNodesRouteImport.update({
  id: '/edit-nodes',
  path: '/edit-nodes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCustomRulesRoute = DocsCustomRulesRouteImport.update({
  id: '/custom-rules',
  path: '/custom-rules',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientSetupRoute = DocsClientSetupRouteImport.update({
  id: '/client-setup',
  path: '/client-setup',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChainProxyRoute = DocsChainProxyRouteImport.update({
  id: '/chain-proxy',
  path: '/chain-proxy',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAboutRoute = DocsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/custom-rules': typeof CustomRulesRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/generator': typeof GeneratorRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRouteWithChildren
  '/probe': typeof ProbeRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/subscribe-files': typeof SubscribeFilesRouteWithChildren
  '/subscription': typeof SubscriptionRouteWithChildren
  '/system-settings': typeof SystemSettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/users': typeof UsersRoute
  '/docs/about': typeof DocsAboutRoute
  '/docs/chain-proxy': typeof DocsChainProxyRoute
  '/docs/client-setup': typeof DocsClientSetupRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/edit-nodes': typeof DocsEditNodesRoute
  '/docs/external-subscriptions': typeof DocsExternalSubscriptionsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/import-subscription': typeof DocsImportSubscriptionRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/login': typeof DocsLoginRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/probe': typeof DocsProbeRoute
  '/docs/proxy-providers': typeof DocsProxyProvidersRoute
  '/docs/proxy-providers-advanced': typeof DocsProxyProvidersAdvancedRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/settings': typeof DocsSettingsRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/subscription-link': typeof DocsSubscriptionLinkRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/traffic-info': typeof DocsTrafficInfoRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/users': typeof DocsUsersRoute
  '/subscribe-files/custom': typeof SubscribeFilesCustomRoute
  '/custom-rules/': typeof CustomRulesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/subscribe-files/': typeof SubscribeFilesIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/generator': typeof GeneratorRoute
  '/login': typeof LoginRoute
  '/probe': typeof ProbeRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/system-settings': typeof SystemSettingsRoute
  '/users': typeof UsersRoute
  '/docs/about': typeof DocsAboutRoute
  '/docs/chain-proxy': typeof DocsChainProxyRoute
  '/docs/client-setup': typeof DocsClientSetupRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/edit-nodes': typeof DocsEditNodesRoute
  '/docs/external-subscriptions': typeof DocsExternalSubscriptionsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/import-subscription': typeof DocsImportSubscriptionRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/login': typeof DocsLoginRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/probe': typeof DocsProbeRoute
  '/docs/proxy-providers': typeof DocsProxyProvidersRoute
  '/docs/proxy-providers-advanced': typeof DocsProxyProvidersAdvancedRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/settings': typeof DocsSettingsRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/subscription-link': typeof DocsSubscriptionLinkRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/traffic-info': typeof DocsTrafficInfoRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/users': typeof DocsUsersRoute
  '/subscribe-files/custom': typeof SubscribeFilesCustomRoute
  '/custom-rules': typeof CustomRulesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/subscribe-files': typeof SubscribeFilesIndexRoute
  '/subscription': typeof SubscriptionIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/custom-rules': typeof CustomRulesRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/generator': typeof GeneratorRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRouteWithChildren
  '/probe': typeof ProbeRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/subscribe-files': typeof SubscribeFilesRouteWithChildren
  '/subscription': typeof SubscriptionRouteWithChildren
  '/system-settings': typeof SystemSettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/users': typeof UsersRoute
  '/docs/about': typeof DocsAboutRoute
  '/docs/chain-proxy': typeof DocsChainProxyRoute
  '/docs/client-setup': typeof DocsClientSetupRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/edit-nodes': typeof DocsEditNodesRoute
  '/docs/external-subscriptions': typeof DocsExternalSubscriptionsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/import-subscription': typeof DocsImportSubscriptionRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/login': typeof DocsLoginRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/probe': typeof DocsProbeRoute
  '/docs/proxy-providers': typeof DocsProxyProvidersRoute
  '/docs/proxy-providers-advanced': typeof DocsProxyProvidersAdvancedRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/settings': typeof DocsSettingsRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/subscription-link': typeof DocsSubscriptionLinkRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/traffic-info': typeof DocsTrafficInfoRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/users': typeof DocsUsersRoute
  '/subscribe-files/custom': typeof SubscribeFilesCustomRoute
  '/custom-rules/': typeof CustomRulesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/subscribe-files/': typeof SubscribeFilesIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/custom-rules'
    | '/docs'
    | '/generator'
    | '/login'
    | '/nodes'
    | '/probe'
    | '/rules'
    | '/settings'
    | '/subscribe-files'
    | '/subscription'
    | '/system-settings'
    | '/templates'
    | '/users'
    | '/docs/about'
    | '/docs/chain-proxy'
    | '/docs/client-setup'
    | '/docs/custom-rules'
    | '/docs/edit-nodes'
    | '/docs/external-subscriptions'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/import-subscription'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/login'
    | '/docs/nodes'
    | '/docs/probe'
    | '/docs/proxy-providers'
    | '/docs/proxy-providers-advanced'
    | '/docs/quick-start'
    | '/docs/settings'
    | '/docs/subscribe-files'
    | '/docs/subscription-link'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/traffic-info'
    | '/docs/update'
    | '/docs/users'
    | '/subscribe-files/custom'
    | '/custom-rules/'
    | '/docs/'
    | '/nodes/'
    | '/subscribe-files/'
    | '/subscription/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/generator'
    | '/login'
    | '/probe'
    | '/rules'
    | '/settings'
    | '/system-settings'
    | '/users'
    | '/docs/about'
    | '/docs/chain-proxy'
    | '/docs/client-setup'
    | '/docs/custom-rules'
    | '/docs/edit-nodes'
    | '/docs/external-subscriptions'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/import-subscription'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/login'
    | '/docs/nodes'
    | '/docs/probe'
    | '/docs/proxy-providers'
    | '/docs/proxy-providers-advanced'
    | '/docs/quick-start'
    | '/docs/settings'
    | '/docs/subscribe-files'
    | '/docs/subscription-link'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/traffic-info'
    | '/docs/update'
    | '/docs/users'
    | '/subscribe-files/custom'
    | '/custom-rules'
    | '/docs'
    | '/nodes'
    | '/subscribe-files'
    | '/subscription'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/custom-rules'
    | '/docs'
    | '/generator'
    | '/login'
    | '/nodes'
    | '/probe'
    | '/rules'
    | '/settings'
    | '/subscribe-files'
    | '/subscription'
    | '/system-settings'
    | '/templates'
    | '/users'
    | '/docs/about'
    | '/docs/chain-proxy'
    | '/docs/client-setup'
    | '/docs/custom-rules'
    | '/docs/edit-nodes'
    | '/docs/external-subscriptions'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/import-subscription'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/login'
    | '/docs/nodes'
    | '/docs/probe'
    | '/docs/proxy-providers'
    | '/docs/proxy-providers-advanced'
    | '/docs/quick-start'
    | '/docs/settings'
    | '/docs/subscribe-files'
    | '/docs/subscription-link'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/traffic-info'
    | '/docs/update'
    | '/docs/users'
    | '/subscribe-files/custom'
    | '/custom-rules/'
    | '/docs/'
    | '/nodes/'
    | '/subscribe-files/'
    | '/subscription/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CustomRulesRoute: typeof CustomRulesRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  GeneratorRoute: typeof GeneratorRoute
  LoginRoute: typeof LoginRoute
  NodesRoute: typeof NodesRouteWithChildren
  ProbeRoute: typeof ProbeRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SubscribeFilesRoute: typeof SubscribeFilesRouteWithChildren
  SubscriptionRoute: typeof SubscriptionRouteWithChildren
  SystemSettingsRoute: typeof SystemSettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-settings': {
      id: '/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe-files': {
      id: '/subscribe-files'
      path: '/subscribe-files'
      fullPath: '/subscribe-files'
      preLoaderRoute: typeof SubscribeFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe': {
      id: '/probe'
      path: '/probe'
      fullPath: '/probe'
      preLoaderRoute: typeof ProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-rules': {
      id: '/custom-rules'
      path: '/custom-rules'
      fullPath: '/custom-rules'
      preLoaderRoute: typeof CustomRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/subscription/': {
      id: '/subscription/'
      path: '/'
      fullPath: '/subscription/'
      preLoaderRoute: typeof SubscriptionIndexRouteImport
      parentRoute: typeof SubscriptionRoute
    }
    '/subscribe-files/': {
      id: '/subscribe-files/'
      path: '/'
      fullPath: '/subscribe-files/'
      preLoaderRoute: typeof SubscribeFilesIndexRouteImport
      parentRoute: typeof SubscribeFilesRoute
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof NodesRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/custom-rules/': {
      id: '/custom-rules/'
      path: '/'
      fullPath: '/custom-rules/'
      preLoaderRoute: typeof CustomRulesIndexRouteImport
      parentRoute: typeof CustomRulesRoute
    }
    '/subscribe-files/custom': {
      id: '/subscribe-files/custom'
      path: '/custom'
      fullPath: '/subscribe-files/custom'
      preLoaderRoute: typeof SubscribeFilesCustomRouteImport
      parentRoute: typeof SubscribeFilesRoute
    }
    '/docs/users': {
      id: '/docs/users'
      path: '/users'
      fullPath: '/docs/users'
      preLoaderRoute: typeof DocsUsersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/update': {
      id: '/docs/update'
      path: '/update'
      fullPath: '/docs/update'
      preLoaderRoute: typeof DocsUpdateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/traffic-info': {
      id: '/docs/traffic-info'
      path: '/traffic-info'
      fullPath: '/docs/traffic-info'
      preLoaderRoute: typeof DocsTrafficInfoRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/templates': {
      id: '/docs/templates'
      path: '/templates'
      fullPath: '/docs/templates'
      preLoaderRoute: typeof DocsTemplatesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/system-settings': {
      id: '/docs/system-settings'
      path: '/system-settings'
      fullPath: '/docs/system-settings'
      preLoaderRoute: typeof DocsSystemSettingsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/system-requirements': {
      id: '/docs/system-requirements'
      path: '/system-requirements'
      fullPath: '/docs/system-requirements'
      preLoaderRoute: typeof DocsSystemRequirementsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/subscription-link': {
      id: '/docs/subscription-link'
      path: '/subscription-link'
      fullPath: '/docs/subscription-link'
      preLoaderRoute: typeof DocsSubscriptionLinkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/subscribe-files': {
      id: '/docs/subscribe-files'
      path: '/subscribe-files'
      fullPath: '/docs/subscribe-files'
      preLoaderRoute: typeof DocsSubscribeFilesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/settings': {
      id: '/docs/settings'
      path: '/settings'
      fullPath: '/docs/settings'
      preLoaderRoute: typeof DocsSettingsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/proxy-providers-advanced': {
      id: '/docs/proxy-providers-advanced'
      path: '/proxy-providers-advanced'
      fullPath: '/docs/proxy-providers-advanced'
      preLoaderRoute: typeof DocsProxyProvidersAdvancedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/proxy-providers': {
      id: '/docs/proxy-providers'
      path: '/proxy-providers'
      fullPath: '/docs/proxy-providers'
      preLoaderRoute: typeof DocsProxyProvidersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/probe': {
      id: '/docs/probe'
      path: '/probe'
      fullPath: '/docs/probe'
      preLoaderRoute: typeof DocsProbeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nodes': {
      id: '/docs/nodes'
      path: '/nodes'
      fullPath: '/docs/nodes'
      preLoaderRoute: typeof DocsNodesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/login': {
      id: '/docs/login'
      path: '/login'
      fullPath: '/docs/login'
      preLoaderRoute: typeof DocsLoginRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install-docker': {
      id: '/docs/install-docker'
      path: '/install-docker'
      fullPath: '/docs/install-docker'
      preLoaderRoute: typeof DocsInstallDockerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install-direct': {
      id: '/docs/install-direct'
      path: '/install-direct'
      fullPath: '/docs/install-direct'
      preLoaderRoute: typeof DocsInstallDirectRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/import-subscription': {
      id: '/docs/import-subscription'
      path: '/import-subscription'
      fullPath: '/docs/import-subscription'
      preLoaderRoute: typeof DocsImportSubscriptionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/generator': {
      id: '/docs/generator'
      path: '/generator'
      fullPath: '/docs/generator'
      preLoaderRoute: typeof DocsGeneratorRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/features': {
      id: '/docs/features'
      path: '/features'
      fullPath: '/docs/features'
      preLoaderRoute: typeof DocsFeaturesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/external-subscriptions': {
      id: '/docs/external-subscriptions'
      path: '/external-subscriptions'
      fullPath: '/docs/external-subscriptions'
      preLoaderRoute: typeof DocsExternalSubscriptionsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/edit-nodes': {
      id: '/docs/edit-nodes'
      path: '/edit-nodes'
      fullPath: '/docs/edit-nodes'
      preLoaderRoute: typeof DocsEditNodesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/custom-rules': {
      id: '/docs/custom-rules'
      path: '/custom-rules'
      fullPath: '/docs/custom-rules'
      preLoaderRoute: typeof DocsCustomRulesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/client-setup': {
      id: '/docs/client-setup'
      path: '/client-setup'
      fullPath: '/docs/client-setup'
      preLoaderRoute: typeof DocsClientSetupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/chain-proxy': {
      id: '/docs/chain-proxy'
      path: '/chain-proxy'
      fullPath: '/docs/chain-proxy'
      preLoaderRoute: typeof DocsChainProxyRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/about': {
      id: '/docs/about'
      path: '/about'
      fullPath: '/docs/about'
      preLoaderRoute: typeof DocsAboutRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface CustomRulesRouteChildren {
  CustomRulesIndexRoute: typeof CustomRulesIndexRoute
}

const CustomRulesRouteChildren: CustomRulesRouteChildren = {
  CustomRulesIndexRoute: CustomRulesIndexRoute,
}

const CustomRulesRouteWithChildren = CustomRulesRoute._addFileChildren(
  CustomRulesRouteChildren,
)

interface DocsRouteChildren {
  DocsAboutRoute: typeof DocsAboutRoute
  DocsChainProxyRoute: typeof DocsChainProxyRoute
  DocsClientSetupRoute: typeof DocsClientSetupRoute
  DocsCustomRulesRoute: typeof DocsCustomRulesRoute
  DocsEditNodesRoute: typeof DocsEditNodesRoute
  DocsExternalSubscriptionsRoute: typeof DocsExternalSubscriptionsRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsFeaturesRoute: typeof DocsFeaturesRoute
  DocsGeneratorRoute: typeof DocsGeneratorRoute
  DocsImportSubscriptionRoute: typeof DocsImportSubscriptionRoute
  DocsInstallDirectRoute: typeof DocsInstallDirectRoute
  DocsInstallDockerRoute: typeof DocsInstallDockerRoute
  DocsLoginRoute: typeof DocsLoginRoute
  DocsNodesRoute: typeof DocsNodesRoute
  DocsProbeRoute: typeof DocsProbeRoute
  DocsProxyProvidersRoute: typeof DocsProxyProvidersRoute
  DocsProxyProvidersAdvancedRoute: typeof DocsProxyProvidersAdvancedRoute
  DocsQuickStartRoute: typeof DocsQuickStartRoute
  DocsSettingsRoute: typeof DocsSettingsRoute
  DocsSubscribeFilesRoute: typeof DocsSubscribeFilesRoute
  DocsSubscriptionLinkRoute: typeof DocsSubscriptionLinkRoute
  DocsSystemRequirementsRoute: typeof DocsSystemRequirementsRoute
  DocsSystemSettingsRoute: typeof DocsSystemSettingsRoute
  DocsTemplatesRoute: typeof DocsTemplatesRoute
  DocsTrafficInfoRoute: typeof DocsTrafficInfoRoute
  DocsUpdateRoute: typeof DocsUpdateRoute
  DocsUsersRoute: typeof DocsUsersRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAboutRoute: DocsAboutRoute,
  DocsChainProxyRoute: DocsChainProxyRoute,
  DocsClientSetupRoute: DocsClientSetupRoute,
  DocsCustomRulesRoute: DocsCustomRulesRoute,
  DocsEditNodesRoute: DocsEditNodesRoute,
  DocsExternalSubscriptionsRoute: DocsExternalSubscriptionsRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsFeaturesRoute: DocsFeaturesRoute,
  DocsGeneratorRoute: DocsGeneratorRoute,
  DocsImportSubscriptionRoute: DocsImportSubscriptionRoute,
  DocsInstallDirectRoute: DocsInstallDirectRoute,
  DocsInstallDockerRoute: DocsInstallDockerRoute,
  DocsLoginRoute: DocsLoginRoute,
  DocsNodesRoute: DocsNodesRoute,
  DocsProbeRoute: DocsProbeRoute,
  DocsProxyProvidersRoute: DocsProxyProvidersRoute,
  DocsProxyProvidersAdvancedRoute: DocsProxyProvidersAdvancedRoute,
  DocsQuickStartRoute: DocsQuickStartRoute,
  DocsSettingsRoute: DocsSettingsRoute,
  DocsSubscribeFilesRoute: DocsSubscribeFilesRoute,
  DocsSubscriptionLinkRoute: DocsSubscriptionLinkRoute,
  DocsSystemRequirementsRoute: DocsSystemRequirementsRoute,
  DocsSystemSettingsRoute: DocsSystemSettingsRoute,
  DocsTemplatesRoute: DocsTemplatesRoute,
  DocsTrafficInfoRoute: DocsTrafficInfoRoute,
  DocsUpdateRoute: DocsUpdateRoute,
  DocsUsersRoute: DocsUsersRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface NodesRouteChildren {
  NodesIndexRoute: typeof NodesIndexRoute
}

const NodesRouteChildren: NodesRouteChildren = {
  NodesIndexRoute: NodesIndexRoute,
}

const NodesRouteWithChildren = NodesRoute._addFileChildren(NodesRouteChildren)

interface SubscribeFilesRouteChildren {
  SubscribeFilesCustomRoute: typeof SubscribeFilesCustomRoute
  SubscribeFilesIndexRoute: typeof SubscribeFilesIndexRoute
}

const SubscribeFilesRouteChildren: SubscribeFilesRouteChildren = {
  SubscribeFilesCustomRoute: SubscribeFilesCustomRoute,
  SubscribeFilesIndexRoute: SubscribeFilesIndexRoute,
}

const SubscribeFilesRouteWithChildren = SubscribeFilesRoute._addFileChildren(
  SubscribeFilesRouteChildren,
)

interface SubscriptionRouteChildren {
  SubscriptionIndexRoute: typeof SubscriptionIndexRoute
}

const SubscriptionRouteChildren: SubscriptionRouteChildren = {
  SubscriptionIndexRoute: SubscriptionIndexRoute,
}

const SubscriptionRouteWithChildren = SubscriptionRoute._addFileChildren(
  SubscriptionRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CustomRulesRoute: CustomRulesRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  GeneratorRoute: GeneratorRoute,
  LoginRoute: LoginRoute,
  NodesRoute: NodesRouteWithChildren,
  ProbeRoute: ProbeRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SubscribeFilesRoute: SubscribeFilesRouteWithChildren,
  SubscriptionRoute: SubscriptionRouteWithChildren,
  SystemSettingsRoute: SystemSettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
